### ISSUE TITLE
Windows doesn't seem to work

### ISSUE THREAD

**Issue by xiaole992** [m-ou-se/pong#4]
: 40 bytes, id=30215, seq=145, encoding=unknown
unknown encoding for ping payload: 3e 3e 3e 3e 54 68 69 73 20 73 74 72 69 6e 67 20 69 73 20 33 32 20 62 79 74 65 73 3c 3c 3c 3c 00

**Comment by m-ou-se** [comment]
Yup. As the readme says, this is a Linux program. :)

**Comment by xiaole992** [comment]
What I mean is, Windows ping cannot produce any effect

**Comment by m-ou-se** [comment]
Oh, sorry, misunderstood.

But yes, that is not going to work: Windows' ping does not put the timestamp in the ping payload. It remembers the timestamps itself and will notice any changes. We cannot trick Windows' ping.

**Comment by xiaole992** [comment]
Thank you for your answer
